import { Maven_Pro } from "next/font/google";
import "../aseets/styles/main.scss";
import MainLayout from "../components/MainLayout";
import PropTypes from "prop-types";

export const maven_Pro = Maven_Pro({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={maven_Pro.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.element,
};
